### ISSUE TITLE
icp load map

### ISSUE THREAD

**Issue by mramezani64** [ori-drs/cdt_challenge#1]
@mauricefallon @benoit-robotics Due to update from ANYbotics, ```icp_load_map_on_launch```  in cdt_challenge/anymal_sim_cdt/launch/ is required to change to ```global_icp_load_map_on_launch```.

**Comment by mauricefallon** [comment]
ok, please make the change and create a pull request. 

the fix has already been made here:
https://github.com/ori-drs/anymal_sim_drs/blob/master/launch/sim.launch#L25

thanks for reporting!
